//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakerSelector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0 °")]
        public string save_ch1ang {
            get {
                return ((string)(this["save_ch1ang"]));
            }
            set {
                this["save_ch1ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45 °")]
        public string save_ch2ang {
            get {
                return ((string)(this["save_ch2ang"]));
            }
            set {
                this["save_ch2ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90 °")]
        public string save_ch3ang {
            get {
                return ((string)(this["save_ch3ang"]));
            }
            set {
                this["save_ch3ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135 °")]
        public string save_ch4ang {
            get {
                return ((string)(this["save_ch4ang"]));
            }
            set {
                this["save_ch4ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180 °")]
        public string save_ch5ang {
            get {
                return ((string)(this["save_ch5ang"]));
            }
            set {
                this["save_ch5ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225 °")]
        public string save_ch6ang {
            get {
                return ((string)(this["save_ch6ang"]));
            }
            set {
                this["save_ch6ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("270 °")]
        public string save_ch7ang {
            get {
                return ((string)(this["save_ch7ang"]));
            }
            set {
                this["save_ch7ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315 °")]
        public string save_ch8ang {
            get {
                return ((string)(this["save_ch8ang"]));
            }
            set {
                this["save_ch8ang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool save_rb_8chsel {
            get {
                return ((bool)(this["save_rb_8chsel"]));
            }
            set {
                this["save_rb_8chsel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int save_cb_chairdeg {
            get {
                return ((int)(this["save_cb_chairdeg"]));
            }
            set {
                this["save_cb_chairdeg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM20")]
        public string save_cb_SerialPort {
            get {
                return ((string)(this["save_cb_SerialPort"]));
            }
            set {
                this["save_cb_SerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_tb_stimulationTime {
            get {
                return ((string)(this["save_tb_stimulationTime"]));
            }
            set {
                this["save_tb_stimulationTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_tb_stimulationTimeWait {
            get {
                return ((string)(this["save_tb_stimulationTimeWait"]));
            }
            set {
                this["save_tb_stimulationTimeWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_tb_routineTime {
            get {
                return ((string)(this["save_tb_routineTime"]));
            }
            set {
                this["save_tb_routineTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool form2Opened {
            get {
                return ((bool)(this["form2Opened"]));
            }
            set {
                this["form2Opened"] = value;
            }
        }
    }
}
